name: Sphinx build
on:
  push:
    paths:
      - 'manual/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build HTML
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "manual/"
        build-command: "sphinx-build -M html . ../build"
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ipe-manual
        path: build/html/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/html
